repos:
    - repo: https://github.com/ambv/black
      rev: stable
      hooks:
        - id: black
          language_version: python3.7
    - repo: git://github.com/pre-commit/pre-commit-hooks
      rev: v2.2.3
      hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: mixed-line-ending
        args: ['--fix=no']
      - id: flake8
        args: [
          '--max-line-length=88', # default of Black
          --ignore=E203
          ]

    - repo: https://github.com/pre-commit/mirrors-isort
      rev: v4.3.4
      hooks:
      - id: isort
        args: ['--trailing-comma', '-m 3', '-tc', '-l 88']

    -   repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
        rev: v1.0.4
        hooks:
        -   id: python-bandit-vulnerability-check
            args: [--ini, .banditrc, -ll, --recursive, src]
